
export const pharmaCompanies = [
  "Abbott",
  "AbbVie",
  "Amgen",
  "AstraZeneca",
  "Avara Pharmaceutical Services",
  "Bausch Health",
  "Baxter",
  "Bayer",
  "Beckman Coulter",
  "Becton Dickinson (BD)",
  "Biogen",
  "Boehringer Ingelheim",
  "Boston Scientific",
  "Bristol Myers Squibb",
  "Cardinal Health",
  "CooperVision",
  "Copan",
  "CytoImmune Therapeutics",
  "Dassault Systèmes",
  "Edwards Lifesciences",
  "Eli Lilly",
  "Fresenius Kabi",
  "Geron",
  "GSK",
  "ICU Medical",
  "Integra LifeSciences",
  "Johnson & Johnson (Janssen)",
  "Medtronic",
  "Merck (MSD)",
  "Neolpharma",
  "Novartis",
  "Novo Nordisk",
  "OMPI (Stevanato Group)",
  "Organon",
  "Pall Corporation",
  "Patheon (Thermo Fisher)",
  "Pfizer",
  "Procter & Gamble (P&G)",
  "QuidelOrtho",
  "Roche",
  "Romark",
  "Sanofi",
  "Sartorius",
  "Stryker",
  "Teva Pharmaceuticals",
  "Thermo Fisher Scientific",
  "Viatris",
  "Zimmer Biomet",
];

export const municipalities = [
  "Adjuntas", "Aguada", "Aguadilla", "Aguas Buenas", "Aibonito",
  "Añasco", "Arecibo", "Arroyo", "Barceloneta", "Barranquitas",
  "Bayamón", "Cabo Rojo", "Caguas", "Camuy", "Canóvanas",
  "Carolina", "Cataño", "Cayey", "Ceiba", "Ciales", "Cidra",
  "Coamo", "Comerío", "Corozal", "Culebra", "Dorado", "Fajardo",
  "Florida", "Guánica", "Guayama", "Guayanilla", "Guaynabo",
  "Gurabo", "Hatillo", "Hormigueros", "Humacao", "Isabela",
  "Jayuya", "Juana Díaz", "Juncos", "Lajas", "Lares",
  "Las Marías", "Las Piedras", "Loíza", "Luquillo", "Manatí",
  "Maricao", "Maunabo", "Mayagüez", "Moca", "Morovis",
  "Naguabo", "Naranjito", "Orocovis", "Patillas", "Peñuelas",
  "Ponce", "Quebradillas", "Rincón", "Río Grande", "Sabana Grande",
  "Salinas", "San Germán", "San Juan", "San Lorenzo", "San Sebastián",
  "Santa Isabel", "Toa Alta", "Toa Baja", "Trujillo Alto", "Utuado",
  "Vega Alta", "Vega Baja", "Vieques", "Villalba", "Yabucoa", "Yauco"
];

export const jobTitles = [
    "Autoclave & Sterilization Engineer",
    "Automation Engineer",
    "Biochemist",
    "Biostatistician",
    "Chemical Engineer",
    "Clinical Research Associate",
    "Compliance Specialist",
    "Data Scientist",
    "EHS Specialist (Environment, Health, and Safety)",
    "Electrical Engineer",
    "Instrumentation Technician",
    "IT Project Manager",
    "Laboratory Technician",
    "Maintenance Manager",
    "Maintenance Technician",
    "Manufacturing Associate/Operator",
    "Manufacturing Engineer",
    "Manufacturing Supervisor",
    "Medical Science Liaison",
    "Metrology Technician",
    "Microbiologist",
    "Packaging Engineer",
    "Process Engineer",
    "Process Validation Engineer",
    "Project Engineer",
    "Project Manager",
    "Purchasing Manager",
    "Quality Assurance Manager",
    "Quality Assurance Specialist",
    "Quality Control Analyst",
    "Quality Engineer",
    "Regulatory Affairs Manager",
    "Regulatory Affairs Specialist",
    "Research Scientist",
    "Supply Chain Planner",
    "Systems Analyst",
    "Technical Writer",
    "Validation Specialist",
];
export const modalities = ["W2", "1099", "480"];
